/**
 * Domain configuration for Healthcare
 * Generated by create-context-graph
 */

export const DOMAIN = {
  id: "healthcare",
  name: "Healthcare",
  description: "Patient care, clinical encounters, diagnoses, treatments, and provider networks",
  tagline: "AI-powered Clinical Intelligence",
};

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

// Origin without the trailing "/api" — the skin-diagnostic image endpoint
// returns paths that already include "/api/...", so building a fetchable
// URL from it means stripping API_BASE's own "/api" suffix first instead of
// concatenating (which would double it up).
export const API_ORIGIN = API_BASE.replace(/\/api\/?$/, "");

export interface GraphData {
  results: Record<string, unknown>[];
}
