/**
 * Domain configuration for Healthcare
 * Generated by create-context-graph
 */

export const DOMAIN = {
  id: "healthcare",
  name: "Healthcare",
  description: "Patient care, clinical encounters, diagnoses, treatments, and provider networks",
  tagline: "AI-powered Clinical Intelligence",
};

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

export interface GraphData {
  results: Record<string, unknown>[];
}
